name: LARAVEL-CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  laravel-setup-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Copy .env
        working-directory: src
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        working-directory: src
        run: composer update && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        working-directory: src
        run: php artisan key:generate
      - name: Directory Permissions
        working-directory: src
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        working-directory: src
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        working-directory: src
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
  laravel-compile-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NPM dependencies
        working-directory: src
        run: npm install
      - name: Compile assets
        working-directory: src
        run: npm run build
  laravel-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker & running
        working-directory: src
        run: docker compose up -d app
